# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/debian/sw_drivers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/debian/sw_drivers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debian/sw_drivers/CMakeFiles /home/debian/sw_drivers/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/debian/sw_drivers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named node

# Build rule for target.
node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 node
.PHONY : node

# fast build rule for target.
node/fast:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/build
.PHONY : node/fast

detection/BGSDetector.o: detection/BGSDetector.cpp.o

.PHONY : detection/BGSDetector.o

# target to build an object file
detection/BGSDetector.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/BGSDetector.cpp.o
.PHONY : detection/BGSDetector.cpp.o

detection/BGSDetector.i: detection/BGSDetector.cpp.i

.PHONY : detection/BGSDetector.i

# target to preprocess a source file
detection/BGSDetector.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/BGSDetector.cpp.i
.PHONY : detection/BGSDetector.cpp.i

detection/BGSDetector.s: detection/BGSDetector.cpp.s

.PHONY : detection/BGSDetector.s

# target to generate assembly for a file
detection/BGSDetector.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/BGSDetector.cpp.s
.PHONY : detection/BGSDetector.cpp.s

detection/ClientUDP.o: detection/ClientUDP.cpp.o

.PHONY : detection/ClientUDP.o

# target to build an object file
detection/ClientUDP.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/ClientUDP.cpp.o
.PHONY : detection/ClientUDP.cpp.o

detection/ClientUDP.i: detection/ClientUDP.cpp.i

.PHONY : detection/ClientUDP.i

# target to preprocess a source file
detection/ClientUDP.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/ClientUDP.cpp.i
.PHONY : detection/ClientUDP.cpp.i

detection/ClientUDP.s: detection/ClientUDP.cpp.s

.PHONY : detection/ClientUDP.s

# target to generate assembly for a file
detection/ClientUDP.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/ClientUDP.cpp.s
.PHONY : detection/ClientUDP.cpp.s

detection/Detector.o: detection/Detector.cpp.o

.PHONY : detection/Detector.o

# target to build an object file
detection/Detector.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/Detector.cpp.o
.PHONY : detection/Detector.cpp.o

detection/Detector.i: detection/Detector.cpp.i

.PHONY : detection/Detector.i

# target to preprocess a source file
detection/Detector.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/Detector.cpp.i
.PHONY : detection/Detector.cpp.i

detection/Detector.s: detection/Detector.cpp.s

.PHONY : detection/Detector.s

# target to generate assembly for a file
detection/Detector.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/Detector.cpp.s
.PHONY : detection/Detector.cpp.s

detection/HOGDetector.o: detection/HOGDetector.cpp.o

.PHONY : detection/HOGDetector.o

# target to build an object file
detection/HOGDetector.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/HOGDetector.cpp.o
.PHONY : detection/HOGDetector.cpp.o

detection/HOGDetector.i: detection/HOGDetector.cpp.i

.PHONY : detection/HOGDetector.i

# target to preprocess a source file
detection/HOGDetector.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/HOGDetector.cpp.i
.PHONY : detection/HOGDetector.cpp.i

detection/HOGDetector.s: detection/HOGDetector.cpp.s

.PHONY : detection/HOGDetector.s

# target to generate assembly for a file
detection/HOGDetector.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/HOGDetector.cpp.s
.PHONY : detection/HOGDetector.cpp.s

detection/Histogram.o: detection/Histogram.cpp.o

.PHONY : detection/Histogram.o

# target to build an object file
detection/Histogram.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/Histogram.cpp.o
.PHONY : detection/Histogram.cpp.o

detection/Histogram.i: detection/Histogram.cpp.i

.PHONY : detection/Histogram.i

# target to preprocess a source file
detection/Histogram.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/Histogram.cpp.i
.PHONY : detection/Histogram.cpp.i

detection/Histogram.s: detection/Histogram.cpp.s

.PHONY : detection/Histogram.s

# target to generate assembly for a file
detection/Histogram.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/Histogram.cpp.s
.PHONY : detection/Histogram.cpp.s

detection/core.o: detection/core.cpp.o

.PHONY : detection/core.o

# target to build an object file
detection/core.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/core.cpp.o
.PHONY : detection/core.cpp.o

detection/core.i: detection/core.cpp.i

.PHONY : detection/core.i

# target to preprocess a source file
detection/core.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/core.cpp.i
.PHONY : detection/core.cpp.i

detection/core.s: detection/core.cpp.s

.PHONY : detection/core.s

# target to generate assembly for a file
detection/core.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/core.cpp.s
.PHONY : detection/core.cpp.s

detection/pugixml.o: detection/pugixml.cpp.o

.PHONY : detection/pugixml.o

# target to build an object file
detection/pugixml.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/pugixml.cpp.o
.PHONY : detection/pugixml.cpp.o

detection/pugixml.i: detection/pugixml.cpp.i

.PHONY : detection/pugixml.i

# target to preprocess a source file
detection/pugixml.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/pugixml.cpp.i
.PHONY : detection/pugixml.cpp.i

detection/pugixml.s: detection/pugixml.cpp.s

.PHONY : detection/pugixml.s

# target to generate assembly for a file
detection/pugixml.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/detection/pugixml.cpp.s
.PHONY : detection/pugixml.cpp.s

drivers/xbgsub.o: drivers/xbgsub.c.o

.PHONY : drivers/xbgsub.o

# target to build an object file
drivers/xbgsub.c.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub.c.o
.PHONY : drivers/xbgsub.c.o

drivers/xbgsub.i: drivers/xbgsub.c.i

.PHONY : drivers/xbgsub.i

# target to preprocess a source file
drivers/xbgsub.c.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub.c.i
.PHONY : drivers/xbgsub.c.i

drivers/xbgsub.s: drivers/xbgsub.c.s

.PHONY : drivers/xbgsub.s

# target to generate assembly for a file
drivers/xbgsub.c.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub.c.s
.PHONY : drivers/xbgsub.c.s

drivers/xbgsub_linux.o: drivers/xbgsub_linux.c.o

.PHONY : drivers/xbgsub_linux.o

# target to build an object file
drivers/xbgsub_linux.c.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub_linux.c.o
.PHONY : drivers/xbgsub_linux.c.o

drivers/xbgsub_linux.i: drivers/xbgsub_linux.c.i

.PHONY : drivers/xbgsub_linux.i

# target to preprocess a source file
drivers/xbgsub_linux.c.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub_linux.c.i
.PHONY : drivers/xbgsub_linux.c.i

drivers/xbgsub_linux.s: drivers/xbgsub_linux.c.s

.PHONY : drivers/xbgsub_linux.s

# target to generate assembly for a file
drivers/xbgsub_linux.c.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub_linux.c.s
.PHONY : drivers/xbgsub_linux.c.s

drivers/xbgsub_sinit.o: drivers/xbgsub_sinit.c.o

.PHONY : drivers/xbgsub_sinit.o

# target to build an object file
drivers/xbgsub_sinit.c.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub_sinit.c.o
.PHONY : drivers/xbgsub_sinit.c.o

drivers/xbgsub_sinit.i: drivers/xbgsub_sinit.c.i

.PHONY : drivers/xbgsub_sinit.i

# target to preprocess a source file
drivers/xbgsub_sinit.c.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub_sinit.c.i
.PHONY : drivers/xbgsub_sinit.c.i

drivers/xbgsub_sinit.s: drivers/xbgsub_sinit.c.s

.PHONY : drivers/xbgsub_sinit.s

# target to generate assembly for a file
drivers/xbgsub_sinit.c.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xbgsub_sinit.c.s
.PHONY : drivers/xbgsub_sinit.c.s

drivers/xfeature.o: drivers/xfeature.c.o

.PHONY : drivers/xfeature.o

# target to build an object file
drivers/xfeature.c.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature.c.o
.PHONY : drivers/xfeature.c.o

drivers/xfeature.i: drivers/xfeature.c.i

.PHONY : drivers/xfeature.i

# target to preprocess a source file
drivers/xfeature.c.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature.c.i
.PHONY : drivers/xfeature.c.i

drivers/xfeature.s: drivers/xfeature.c.s

.PHONY : drivers/xfeature.s

# target to generate assembly for a file
drivers/xfeature.c.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature.c.s
.PHONY : drivers/xfeature.c.s

drivers/xfeature_linux.o: drivers/xfeature_linux.c.o

.PHONY : drivers/xfeature_linux.o

# target to build an object file
drivers/xfeature_linux.c.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature_linux.c.o
.PHONY : drivers/xfeature_linux.c.o

drivers/xfeature_linux.i: drivers/xfeature_linux.c.i

.PHONY : drivers/xfeature_linux.i

# target to preprocess a source file
drivers/xfeature_linux.c.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature_linux.c.i
.PHONY : drivers/xfeature_linux.c.i

drivers/xfeature_linux.s: drivers/xfeature_linux.c.s

.PHONY : drivers/xfeature_linux.s

# target to generate assembly for a file
drivers/xfeature_linux.c.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature_linux.c.s
.PHONY : drivers/xfeature_linux.c.s

drivers/xfeature_sinit.o: drivers/xfeature_sinit.c.o

.PHONY : drivers/xfeature_sinit.o

# target to build an object file
drivers/xfeature_sinit.c.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature_sinit.c.o
.PHONY : drivers/xfeature_sinit.c.o

drivers/xfeature_sinit.i: drivers/xfeature_sinit.c.i

.PHONY : drivers/xfeature_sinit.i

# target to preprocess a source file
drivers/xfeature_sinit.c.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature_sinit.c.i
.PHONY : drivers/xfeature_sinit.c.i

drivers/xfeature_sinit.s: drivers/xfeature_sinit.c.s

.PHONY : drivers/xfeature_sinit.s

# target to generate assembly for a file
drivers/xfeature_sinit.c.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/drivers/xfeature_sinit.c.s
.PHONY : drivers/xfeature_sinit.c.s

maxi_new.o: maxi_new.cpp.o

.PHONY : maxi_new.o

# target to build an object file
maxi_new.cpp.o:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/maxi_new.cpp.o
.PHONY : maxi_new.cpp.o

maxi_new.i: maxi_new.cpp.i

.PHONY : maxi_new.i

# target to preprocess a source file
maxi_new.cpp.i:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/maxi_new.cpp.i
.PHONY : maxi_new.cpp.i

maxi_new.s: maxi_new.cpp.s

.PHONY : maxi_new.s

# target to generate assembly for a file
maxi_new.cpp.s:
	$(MAKE) -f CMakeFiles/node.dir/build.make CMakeFiles/node.dir/maxi_new.cpp.s
.PHONY : maxi_new.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... node"
	@echo "... edit_cache"
	@echo "... detection/BGSDetector.o"
	@echo "... detection/BGSDetector.i"
	@echo "... detection/BGSDetector.s"
	@echo "... detection/ClientUDP.o"
	@echo "... detection/ClientUDP.i"
	@echo "... detection/ClientUDP.s"
	@echo "... detection/Detector.o"
	@echo "... detection/Detector.i"
	@echo "... detection/Detector.s"
	@echo "... detection/HOGDetector.o"
	@echo "... detection/HOGDetector.i"
	@echo "... detection/HOGDetector.s"
	@echo "... detection/Histogram.o"
	@echo "... detection/Histogram.i"
	@echo "... detection/Histogram.s"
	@echo "... detection/core.o"
	@echo "... detection/core.i"
	@echo "... detection/core.s"
	@echo "... detection/pugixml.o"
	@echo "... detection/pugixml.i"
	@echo "... detection/pugixml.s"
	@echo "... drivers/xbgsub.o"
	@echo "... drivers/xbgsub.i"
	@echo "... drivers/xbgsub.s"
	@echo "... drivers/xbgsub_linux.o"
	@echo "... drivers/xbgsub_linux.i"
	@echo "... drivers/xbgsub_linux.s"
	@echo "... drivers/xbgsub_sinit.o"
	@echo "... drivers/xbgsub_sinit.i"
	@echo "... drivers/xbgsub_sinit.s"
	@echo "... drivers/xfeature.o"
	@echo "... drivers/xfeature.i"
	@echo "... drivers/xfeature.s"
	@echo "... drivers/xfeature_linux.o"
	@echo "... drivers/xfeature_linux.i"
	@echo "... drivers/xfeature_linux.s"
	@echo "... drivers/xfeature_sinit.o"
	@echo "... drivers/xfeature_sinit.i"
	@echo "... drivers/xfeature_sinit.s"
	@echo "... maxi_new.o"
	@echo "... maxi_new.i"
	@echo "... maxi_new.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

